### ISSUE TITLE
slugification:  id field is not accounted for

### ISSUE THREAD

**Issue by christher-lenander** [ComfortablyCoding/strapi-plugin-slugify#28] opened 2022-03-01 10:04 UTC
I tested to make the references property as an array with fields. When I do so the slug is left empty when saving the post (create and update).
![image](https://user-images.githubusercontent.com/49711748/156148340-95ea52cb-3e17-4d28-a504-d03a4c26d983.png)

**Comment by ComfortablyCoding** [comment] 2022-03-01 13:45
It is due to the id being prefedined attribute and not being included in the schema. I will add a fix for this.

**Comment by ChristherLenander** [comment] 2022-03-01 13:50
Ah. I notice that if I added other fields it worked.

**Comment by SoftCreatR** [comment] 2022-03-02 07:02
Was going to report the same. Thank you for fixing it :)

**Comment by ChristherLenander** [comment] 2022-03-07 18:09
What is the status for this?

**Comment by ComfortablyCoding** [comment] 2022-03-08 00:46
The problem is that id is not generated until after the entry has been created. It also is not in the same data object as the rest of the properties.

Due to this the implementation requires a change to the lifecycle events being used and how slugs are generated. It will take a a bit more tine to come up with an optimal solution.

**Comment by ComfortablyCoding** [comment] 2022-03-10 03:33
I am going to wait for strapi/strapi#12203 to be merged as it should make things easier.

**Comment by SoftCreatR** [comment] 2022-03-15 01:00
Alternative: https://github.com/strapi/strapi/pull/12834

**Comment by LiquidITGuy** [comment] 2022-09-20 16:34
Any updates about this issue ? (we got other issues when trying to inject data with etl with same title (the slug-with-count try to insert the same count and this issue may fix it waiting to have a fix for the concurrent insertion)) (I will open an issue tomorrow

**Comment by aida-b-f** [comment] 2022-09-29 12:11
> Any updates about this issue ? (we got other issues when trying to inject data with etl with same title (the slug-with-count try to insert the same count and this issue may fix it waiting to have a fix for the concurrent insertion)) (I will open an issue tomorrow

We have this same issue with the counter. Super annoying. 
The Strapi built in slug system has a better counter/validity check on the slug but it has other issues such as stripping the reference field, that's why I switched to this plugin. Worked fine as long as we didn't create more than 2 posts with the same title 😃 

Any update if this issue will be resolved would be appreciated.

**Comment by shivam-raj** [comment] 2022-10-05 11:56
Got the same issue while trying to insert with the same name. 
Slugs are generated according to name of the person. We thought of using username as the slug but turns out when you use a Social Provider to login in Strapiv4, even the username generated isn't unique.

We are generating content via API and that is why we moved to this plugin. Now we can not generate unique slugs for same name even with slugifyWithCount set to true. Fails with the message : UNIQUE constraint failed.

Any workaround for this?
Thanks in advance!

**Closed** 2022-10-25 01:10 UTC
Labels: enhancement

**Comment by ComfortablyCoding** [comment] 2022-10-25 02:02
Should be supported in v2.3.1
