### ISSUE TITLE
Internal server error when requesting unpublished page

### ISSUE THREAD

**Issue by superpep** [ComfortablyCoding/strapi-plugin-slugify#38] opened 2022-03-15 08:20 UTC
Whenever I use slugify to visit a published page, it retrieves the data without a problem. But, when I **unpublish** the page, it gives an **Internal Server error** when it should be a **Not Found error**. 

This is an example accessing a **unpublished** page:
![Screenshot 2022-03-15 at 09-11-44 Screenshot](https://user-images.githubusercontent.com/37349590/158334694-5a2d5b97-d47e-41fb-9077-74047e3cd26d.png)

This is an example accessing a **published** page:
![Screenshot 2022-03-15 at 09-17-21 Screenshot](https://user-images.githubusercontent.com/37349590/158334896-d805c3ba-025c-4851-ba4e-b87302e0b4bb.png)

LOGs:
![Captura de pantalla de 2022-03-15 09-19-29](https://user-images.githubusercontent.com/37349590/158335283-9502dc54-689e-4c23-be7b-d17dfea48bf8.png)

Slugify version: `2.0.0`
Strapi version: `4.1.2`

**Comment by ComfortablyCoding** [comment] 2022-03-16 00:08
I tested on the latest slugify version and I cannot reproduce this issue. Can you update the slugify version to latest and see if the issue still persists?

**Comment by ComfortablyCoding** [comment] 2022-03-20 01:24
Closing for now. If a reproducible example is provided it can be investigated futher.

**Closed by ComfortablyCoding** 2022-03-20 01:24 UTC
