### ISSUE TITLE
Field does not auto generate

### ISSUE THREAD

**Issue by iRyteRong** [ComfortablyCoding/strapi-plugin-slugify#65] opened 2022-06-21 00:44 UTC
I am using a UUID because the text never worked automatically. The slug does not auto-generate to the name. It shows the name of the content type. Am I missing something with the plugin?

These are my settings :
` slugify: {
    enabled: true,
    config: {
      contentTypes: {
        service: {
          field: "slug",
          references: "name",
        },
      },
    },`

**Comment by ComfortablyCoding** [comment] 2022-06-23 23:45
Do you have a sample repo that reproduces this issue that I can take a look at? Not exactly sure what you mean by its not auto generated with text. It works fine for me.

**Comment by ComfortablyCoding** [comment] 2022-07-13 02:42
Closing due to no reproducible example provided.

**Closed by ComfortablyCoding** 2022-07-13 02:42 UTC
