### ISSUE TITLE
Cannot read properties of undefined (reading 'admin::permission') strapi 4.1.7

### ISSUE THREAD

**Issue by talbenyam** [ComfortablyCoding/strapi-plugin-slugify#51] opened 2022-04-07 21:05 UTC
[2022-04-07 23:32:20.574] info: [slugify] graphql detected, registering queries
[2022-04-07 23:32:20.917] debug: ⛔️ Server wasn't able to start properly.
[2022-04-07 23:32:20.918] error: Cannot read properties of undefined (reading 'admin::permission')
TypeError: Cannot read properties of undefined (reading 'admin::permission')

**Comment by ComfortablyCoding** [comment] 2022-04-08 01:06
duplicate of #35

**Closed by ComfortablyCoding** 2022-04-08 01:06 UTC
