### ISSUE TITLE
Changing titles back and forth to the original title causes the slug count to increase

### ISSUE THREAD

**Issue by IHIutch** [ComfortablyCoding/strapi-plugin-slugify#58] opened 2022-05-17 04:22 UTC
If I have a post titled `A` and change it to `B` and then back to `A` again, the slug will become `a-2`.

Continuing to change the titles back and forth continues the count.

This could be a problem if you change a title but later decide to change it back. (Or in my circumstance, debugging purposes)

**Comment by ComfortablyCoding** [comment] 2022-05-23 18:32
Yes, this is intended behaviour.

If you change the title back and forth or update the post with the title field present in the body it will treat it as a new title. We can potentially mitigate this by adding a check if the title is exactly the same for the entity in question. That will not account for other entity records that have the same number though.

The slugify with count is not an ideal way to uniquely identiy slugs. I would suggest using the entity id as part of the composite reference. At the moment adding the id as a reference does not work due to a bug that was in strapi. Now that the PR fix was merged I plan to fix the issue within the next week or so.

**Closed by ComfortablyCoding** 2022-05-23 18:32 UTC
